version: "3.8"

services:
  broker:
    build: ./broker
    container_name: iot-broker
    environment:
      BROKER_PORT: 1883
    networks:
      - iot-network

  monitor:
    build: ./monitor
    container_name: iot-monitor
    environment:
      BROKER_HOST: iot-broker
      BROKER_PORT: 1883
    networks:
      - iot-network
    depends_on:
      - broker
    command: [ "./scripts/wait-for", "iot-broker:1883", "--", "node", "index.js"]

  end_device:
    build: ./end_device
    container_name: iot-end_device
    environment:
      BROKER_HOST: iot-broker
      BROKER_PORT: 1883
    networks:
      - iot-network
    depends_on:
      - broker
    command: [ "./scripts/wait-for", "iot-broker:1883", "--", "node", "index.js"]

networks:
  iot-network:
