version: "3.8"

services:
  broker:
    build: ./broker
    container_name: broker
    environment:
      BROKER_PORT: 1883
    networks:
      - iot-network

  monitor:
    build: ./monitor
    container_name: monitor
    environment:
      NAME: mon0
      END_DEVICES: 'end0 end1'
      BROKER_HOST: broker
      BROKER_PORT: 1883
    networks:
      - iot-network
    depends_on:
      - broker
    command: [ "./scripts/wait-for", "broker:1883", "--", "node", "index.js"]

  end_device_0:
    build: ./end_device
    container_name: end_device_0
    environment:
      NAME: end0
      BROKER_HOST: broker
      BROKER_PORT: 1883
    networks:
      - iot-network
    depends_on:
      - broker
    command: [ "./scripts/wait-for", "broker:1883", "--", "node", "index.js"]

  end_device_1:
    build: ./end_device
    container_name: end_device_1
    environment:
      NAME: end1
      BROKER_HOST: broker
      BROKER_PORT: 1883
    networks:
      - iot-network
    depends_on:
      - broker
    command: [ "./scripts/wait-for", "broker:1883", "--", "node", "index.js"]

networks:
  iot-network:
