version: "3.8"

services:
  broker:
    build: ./broker
    container_name: broker
    environment:
      BROKER_PORT: 1883
    networks:
      - iot-network

  monitor:
    build: ./monitor
    container_name: monitor
    environment:
      NAME: mon
      END_DEVICES: 'end'
      BROKER_HOST: broker
      BROKER_PORT: 1883
    networks:
      - iot-network
    depends_on:
      - broker
    command: [ "./scripts/wait-for", "broker:1883", "--", "node", "index.js"]

  end_device:
    build: ./end_device
    environment:
      NAME: end
      BROKER_HOST: broker
      BROKER_PORT: 1883
    networks:
      - iot-network
    depends_on:
      - broker
    command: [ "./scripts/wait-for", "broker:1883", "--", "node", "index.js"]

networks:
  iot-network:
